name: network_arch
description:
  NetworkArch is a network diagnostic tool equipped with various utilities,
  including pinging specific IP address or hostname, sending Wake on LAN magic packets,
  whois and DNS Lookup.
publish_to: "none"
version: 2.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adapty_flutter: ^2.9.2
  animate_do: ^3.3.3
  bloc: ^8.1.3
  carrier_info: ^2.0.8
  cupertino_icons: ^1.0.6
  cupertino_onboarding: ^1.2.0
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  dynamic_color: ^1.4.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_platform_widgets: ^6.1.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  google_mobile_ads: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  hydrated_bloc: ^9.1.4
  in_app_review: ^2.0.8
  introduction_screen: ^3.1.12
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lan_scanner: ^4.0.0+1
  mocktail: ^1.0.3
  modal_bottom_sheet: ^3.0.0-pre
  network_info_plus: ^4.1.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  sentry_flutter: ^7.16.1
  url_launcher: ^6.2.5
  wake_on_lan: ^4.1.1
  wiredash: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/dark_mode_map_style.txt
    - assets/icons/icon_alpha_light.svg
    - assets/icons/icon_alpha_dark.svg
